name: Nightly

on:
  schedule:
  - cron:  "0 6 * * *"
  # allow manual trigger
  workflow_dispatch:

jobs:
  request-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        snap:
          - edgexfoundry
          - edgex-cli
          - edgex-ui
          - edgex-app-service-configurable
          - edgex-app-rfid-llrp-inventory
          - edgex-device-camera
          - edgex-device-gpio
          - edgex-device-modbus
          - edgex-device-mqtt
          - edgex-device-rest
          - edgex-device-rfid-llrp
          - edgex-device-snmp
          - edgex-device-usb-camera
          - edgex-device-virtual
        arch: [amd64, arm64]
        include:
          # Use Ubuntu 20.04 by default
          - ubuntu_series: focal
          # Additional armhf build for device-gpio
          - snap: edgex-device-gpio
            arch: armhf
          # Use Ubuntu 22.04 for device-usb-camera
          - snap: edgex-device-usb-camera
            ubuntu_series: jammy
    steps:        
      - name: Kick off Launchpad build
        uses: canonical/edgex-launchpad-build-action@split-build-script
        with:
          snap_name: ${{ matrix.snap }}
          architecture: ${{ matrix.arch }}
          ubuntu_series: ${{ matrix.ubuntu_series }}
          consumer_name: ${{ secrets.LP_CONSUMER_NAME }}
          access_token: ${{ secrets.LP_ACCESS_TOKEN }}
          access_secret: ${{ secrets.LP_ACCESS_SECRET }}

  # To keep the workflow active,
  # add a commit if the project hasn't been active for 59 days.
  # See https://github.com/canonical/edgex-sync/issues/20
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/keepalive-workflow@master
        with:
          committer_username: github-actions[bot]
          committer_email: github-actions[bot]@users.noreply.github.com
          time_elapsed: 59
