name: Nightly

on:
  pull_request:
  schedule:
  - cron:  "0 6 * * *"

jobs:
  request-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        architecture: [amd64, arm64]
        snap:
          - edgexfoundry
          - edgex-cli
          - edgex-ui
          - edgex-app-service-configurable
          - edgex-app-rfid-llrp-inventory
          - edgex-device-camera
          - edgex-device-gpio
          - edgex-device-modbus
          - edgex-device-mqtt
          - edgex-device-rest
          - edgex-device-rfid-llrp
          - edgex-device-snmp
          - edgex-device-virtual
        include:
          # Additional armhf build for device-gpio
          - snap: edgex-device-gpio
            architecture: armhf
    steps:        
      - name: Kick off Launchpad build
        uses: canonical/edgex-launchpad-build-action@v1.8
        with:
          edgex_snap: ${{ matrix.snap }}
          consumer_name: ${{ secrets.LP_CONSUMER_NAME }}
          access_token: ${{ secrets.LP_ACCESS_TOKEN }}
          access_secret: ${{ secrets.LP_ACCESS_SECRET }}
          architecture: ${{ matrix.architecture }}
