name: Nightly

on:
  workflow_dispatch:
  schedule:
  - cron:  "0 6 * * *"

jobs:
  request-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        snap:
          - edgexfoundry
          - edgex-cli
          - edgex-ui
          - edgex-app-service-configurable
          - edgex-app-rfid-llrp-inventory
          - edgex-device-camera
          - edgex-device-gpio
          - edgex-device-modbus
          - edgex-device-mqtt
          - edgex-device-rest
          - edgex-device-rfid-llrp
          - edgex-device-snmp
          - edgex-device-virtual
        arch: [amd64, arm64]
        include:
          # Additional armhf build for device-gpio
          - snap: edgex-device-gpio
            arch: armhf
    steps:        
      - name: Kick off Launchpad build
        uses: canonical/edgex-launchpad-build-action@v2.0
        with:
          snap_name: ${{ matrix.snap }}
          architecture: ${{ matrix.arch }}
          consumer_name: ${{ secrets.LP_CONSUMER_NAME }}
          access_token: ${{ secrets.LP_ACCESS_TOKEN }}
          access_secret: ${{ secrets.LP_ACCESS_SECRET }}
          
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run keepalive workflow
        uses: gautamkrishnar/keepalive-workflow@master
        with:
          commit_message: keepalive
          committer_username: github-actions[bot]
          committer_email: github-actions[bot]@users.noreply.github.com
