name: EdgeX-Device-Camera
on:
  schedule:
  - cron:  "0 6 * * *"
jobs:
  build-snap:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: edgexfoundry/device-camera-go
        fetch-depth: 0
        ref: main
    - name: Build the snap
      uses: snapcore/action-build@v1
    - name: Uploading snap artifact
      uses: actions/upload-artifact@v2
      with:
        name: snap-files
        path: "*.snap"   
    # testing disabled for this snap until it has been moved to v2
    #- name: Test the snap
    #  uses: canonical/edgex-test-device-snap-action@v1.5
    #  with:
    #    edgex_device_snap: "edgex-device-camera"
    #    edgex_service_name: "device-camera"
    #    edgex_device_name: "Camera001"
    - name: MM Failure
      if: ${{ failure() }}
      run: |
        curl -i -X POST -H 'Content-Type: application/json' -d '{"username" : "github-builds", "text" : "<!channel> :warning: Build/test failed [${{github.event_name}}] ${{github.workflow}} [See logs](https://github.com/canonical/edgex-sync/actions/runs/${{github.run_id}}) "}' ${{secrets.MATTERMOST}}
  build-launchpad:
    runs-on: ubuntu-latest
    needs:  build-snap
    steps:
      - name: Kick off Launchpad build
        uses: canonical/edgex-launchpad-build-action@v1.7
        with:
          build1: "amd64"
          build2: "arm64"
          edgex_snap: "edgex-device-camera"
          consumer_name: ${{ secrets.LP_CONSUMER_NAME }}
          access_token: ${{ secrets.LP_ACCESS_TOKEN }}
          access_secret: ${{ secrets.LP_ACCESS_SECRET }}
      - name: MM Failure
        if: ${{ failure() }}
        run: |
          curl -i -X POST -H 'Content-Type: application/json' -d '{"username" : "github-builds", "text" : "<!channel> :warning: Launchpad build failed [${{github.event_name}}] ${{github.workflow}} [See logs](https://github.com/canonical/edgex-sync/actions/runs/${{github.run_id}}) "}' ${{secrets.MATTERMOST}}
